// Generated by https://quicktype.io

export interface CryptoResponse {
    timestamp: number;
    data:      Crypto[];
}

export interface Crypto {
    id:                string;
    rank:              string;
    symbol:            string;
    name:              string;
    supply:            string;
    maxSupply:         null | string;
    marketCapUsd:      string;
    volumeUsd24Hr:     string;
    priceUsd:          string;
    changePercent24Hr: string;
    vwap24Hr:          string;
    explorer:          null | string;
}
