// Generated by https://quicktype.io

export interface HistoryResponse {
    timestamp: number;
    data:      History[];
}

export interface History {
    circulatingSupply: number;
    priceUsd:          string;
    time:              number;
    date:              Date;
}
